name: leagueofgoons
services:
  db:
    image: ncolondres/leagueofgoons-db
    env_file:
      - ${ENV_FILE:-.env}
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    ports:
      - 32769:3306
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    image: ncolondres/leagueofgoons-api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
      args:
        - ENV_FILE=${ENV_FILE:-.env}
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
  sentinel:
    image: ncolondres/leagueofgoons-sentinel
    build:
      context: ./
      dockerfile: ./sentinel/Dockerfile
      args:
        - ENV_FILE=${ENV_FILE:-.env}
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
  web:
    image: ncolondres/leagueofgoons-web
    build:
      context: ./
      dockerfile: ./web/Dockerfile
      args:
        - ENV_FILE=${ENV_FILE:-.env}
    depends_on:
      api:
        condition: service_started
    ports:
      - 4173:4173
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./web/dist
volumes:
  mysql-data:
