name: leagueofgoons
services:
  db:
    image: ncolondres/leagueofgoons-db
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    ports:
      - 32769:3306
  api:
    image: ncolondres/leagueofgoons-api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
  sentinel:
    image: ncolondres/leagueofgoons-sentinel
    build:
      context: ./
      dockerfile: ./sentinel/Dockerfile
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
  web:
    image: ncolondres/leagueofgoons-web
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    depends_on:
      api:
        condition: service_started
    ports:
      - 4173:4173
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./web/dist
          target: /app/dist
