CREATE DATABASE IF NOT EXISTS lol;

CREATE TABLE IF NOT EXISTS lol.lobbies (
    id VARCHAR(17) PRIMARY KEY,
    creation_time TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator_puuid VARCHAR(80) NOT NULL,
    started BOOLEAN DEFAULT FALSE NOT NULL,
    started_time TIMESTAMP,
    matches TINYINT,
    last_processed TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lol.players (
    puuid VARCHAR(80) PRIMARY KEY,
    id VARCHAR(65) NOT NULL,
    account_id VARCHAR(60) NOT NULL,
    profile_icon_id SMALLINT UNSIGNED NOT NULL,
    revision_date BIGINT UNSIGNED NOT NULL,
    level SMALLINT UNSIGNED NOT NULL,
    name VARCHAR(25) NOT NULL,
    region VARCHAR(4) NOT NULL,
    lobby_id VARCHAR(25),
    last_match TIMESTAMP,
    total_score MEDIUMINT UNSIGNED DEFAULT 0 NOT NULL,
    completed BOOLEAN DEFAULT FALSE NOT NULL,
    FOREIGN KEY (lobby_id)
        REFERENCES lobbies(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lol.lobby_points_multipliers (
    lobby_id VARCHAR(25) PRIMARY KEY,
    k_d_a SMALLINT UNSIGNED NOT NULL,
    baron SMALLINT UNSIGNED NOT NULL,
    inhib SMALLINT UNSIGNED NOT NULL,
    dragon SMALLINT UNSIGNED NOT NULL,
    turret SMALLINT UNSIGNED NOT NULL,
    penta SMALLINT UNSIGNED NOT NULL,
    quadra SMALLINT UNSIGNED NOT NULL,
    triple SMALLINT UNSIGNED NOT NULL,
    `double` SMALLINT UNSIGNED NOT NULL,
    rift SMALLINT UNSIGNED NOT NULL,
    vision SMALLINT UNSIGNED NOT NULL,
    win SMALLINT UNSIGNED NOT NULL,
    creep FLOAT UNSIGNED NOT NULL,
    FOREIGN KEY (lobby_id)
        REFERENCES lobbies(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lol.matches (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    match_id VARCHAR(15) NOT NULL,
    player_puuid VARCHAR(80) NOT NULL,
    champion VARCHAR(30) NOT NULL,
    position VARCHAR(15) NOT NULL,
    kills TINYINT UNSIGNED NOT NULL,
    deaths TINYINT UNSIGNED NOT NULL,
    assists TINYINT UNSIGNED NOT NULL,
    turrets TINYINT UNSIGNED NOT NULL,
    inhibs TINYINT UNSIGNED NOT NULL,
    dragons TINYINT UNSIGNED NOT NULL,
    rifts TINYINT UNSIGNED NOT NULL,
    barons TINYINT UNSIGNED NOT NULL,
    vision_score TINYINT UNSIGNED NOT NULL,
    creep_score SMALLINT UNSIGNED NOT NULL,
    pentas TINYINT UNSIGNED NOT NULL,
    quadras TINYINT UNSIGNED NOT NULL,
    triples TINYINT UNSIGNED NOT NULL,
    doubles TINYINT UNSIGNED NOT NULL,
    win BOOLEAN NOT NULL,
    game_end_timestamp TIMESTAMP NOT NULL,
    calculated BOOLEAN DEFAULT FALSE,
    UNIQUE (match_id, player_puuid),
    FOREIGN KEY (player_puuid)
        REFERENCES players(puuid)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE EVENT expired_lobby_removal
ON SCHEDULE EVERY 1 HOUR
ON COMPLETION PRESERVE
DO
DELETE FROM lol.lobbies
WHERE TIMESTAMPDIFF(DAY, creation_time , NOW()) > 9 ;